gazebo_ros_control:
  pid_gains:
    prbt_joint_1: {p: 50000.0, i: 1,    d: 0.0}
    prbt_joint_2: {p: 50000.0, i: 1,    d: 0.0}
    prbt_joint_3: {p: 50000.0, i: 1,    d: 0.0}
    prbt_joint_4: {p: 5000.0,  i: 0.1,  d: 0.0}
    prbt_joint_5: {p: 5000.0,  i: 0.1,  d: 0.0}
    prbt_joint_6: {p: 5000.0,  i: 0.1,  d: 0.0}