gazebo_ros_control:
  pid_gains:
    prbt_joint_1: {p: 1000.0, i: 0.01, d: 0.0}
    prbt_joint_2: {p: 1000.0, i: 0.01, d: 0.0}
    prbt_joint_3: {p: 1000.0, i: 0.01, d: 0.0}
    prbt_joint_4: {p: 1000.0, i: 0.01, d: 0.0}
    prbt_joint_5: {p: 1000.0, i: 0.01, d: 0.0}
    prbt_joint_6: {p: 1000.0, i: 0.01, d: 0.0}