# Operation mode: Disabled per default, can be enabled in robot.launch with parameter "has_operation_mode_support"
OPERATION_MODE: 970 # 0 = No Operation mode, 1 = T1, 2 = T2, 3 = Automatik, Operation modes according to EN ISO 10218

# Braketest: Disabled per default, can be enabled in robot.launch with parameter "has_braketest_support"
BRAKETEST_REQUEST: 973 # 0 = Test not required, 1 = Test required

# Generic: Enabled the whole time
RUN_PERMITTED: 974 # robot is only allowed to move when the signal is 1
VERSION: 977 # version of modbus register specification
