#!/usr/bin/env python

import sys

from pilz_status_indicator_rqt.status_indicator import PilzStatusIndicatorRqt
from rqt_gui.main import Main

plugin = 'pilz_status_indicator_rqt.status_indicator.PilzStatusIndicatorRqt'
main = Main(filename=plugin)
# starting and rqt instance with the -t flag to make it float on top of other windows.
sys.exit(main.main(standalone=plugin, argv=sys.argv + ['-t']))
