#!/usr/bin/env python

import sys

from pilz_status_indicator_rqt.status_indicator import PilzStatusIndicatorRqt
from rqt_gui.main import Main

plugin = 'pilz_status_indicator_rqt.status_indicator.PilzStatusIndicatorRqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
