#
# Copyright © 2018 Pilz GmbH & Co. KG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FILE DESCRIPTION:
#
# This file declares the different controller types which can then be
# instanciated by the controller manager. In this file only controllers
# for the manipulator are declared (no gripper).
# 
# See also: http://wiki.ros.org/joint_trajectory_controller?distro=lunar
#

## joint_names
joint_names: [prbt_joint_1, prbt_joint_2, prbt_joint_3, prbt_joint_4, prbt_joint_5, prbt_joint_6]

## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller (needed to obtain /joint_states)
manipulator_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
manipulator_joint_trajectory_controller:
  type: position_controllers/PilzJointTrajectoryController
  joints:
     - prbt_joint_1
     - prbt_joint_2
     - prbt_joint_3
     - prbt_joint_4
     - prbt_joint_5
     - prbt_joint_6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      prbt_joint_1: {trajectory: 0.157, goal: 0.01}
      prbt_joint_2: {trajectory: 0.157, goal: 0.01}
      prbt_joint_3: {trajectory: 0.157, goal: 0.01}
      prbt_joint_4: {trajectory: 0.157, goal: 0.01}
      prbt_joint_5: {trajectory: 0.157, goal: 0.01}
      prbt_joint_6: {trajectory: 0.157, goal: 0.01}
  stop_trajectory_duration: 0.2
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7
  limits:
      prbt_joint_1:
        has_acceleration_limits: true
        max_acceleration: 4.0
      prbt_joint_2:
        has_acceleration_limits: true
        max_acceleration: 4.0
      prbt_joint_3:
        has_acceleration_limits: true
        max_acceleration: 4.0
      prbt_joint_4:
        has_acceleration_limits: true
        max_acceleration: 4.0
      prbt_joint_5:
        has_acceleration_limits: true
        max_acceleration: 4.0
      prbt_joint_6:
        has_acceleration_limits: true
        max_acceleration: 4.0
